description: >
  This is the default executor for the org, do not change it
docker:
  - image: ghcr.io/giovannicandido/kugelbit-message-bot:<<parameters.tag>>
parameters:
  resource_class:
    default: small
    description: Configure the executor resource class
    enum:
      - small
      - medium
      - medium+
      - large
      - xlarge
      - 2xlarge
      - 2xlarge+
    type: enum
  tag:
    default: main
    description: >
      Pick a specific ghcr.io/giovannicandido/kugelbit-message-bot image variant:
      https://github.com/giovannicandido/kugelbit-message-bot/pkgs/container/kugelbit-message-bot
    type: string
resource_class: << parameters.resource_class >>
