description: >
  This is the default executor for the org, do not change it
docker:
  - image: ghcr.io/giovannicandido/kugelbit-message-bot:<<parameters.tag>>
    resource_class: small
parameters:
  tag:
    default: main
    description: >
      Pick a specific ghcr.io/giovannicandido/kugelbit-message-bot image variant:
      https://github.com/giovannicandido/kugelbit-message-bot/pkgs/container/kugelbit-message-bot
    type: string
